import { BrowserWindow } from 'electron'
import constants from '../constants'
import { isDevelopment } from '../helpers/is-dev'
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string

export function createWindow(): void {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: constants.WindowBounds.height,
    width: constants.WindowBounds.width,
    minHeight: constants.WindowMinBounds.height,
    minWidth: constants.WindowMinBounds.width,
    frame: false,
    titleBarStyle: 'hiddenInset'
  })

  mainWindow.removeMenu()

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  if (isDevelopment()) {
    // Open the DevTools.
    mainWindow.webContents.openDevTools()
  }
}
